### ISSUE TITLE
Wavelog Cluster

### ISSUE THREAD

**Issue by HRui-Z** [tanilolli/CloudlogTCI#6]
Hi Anthony,

I just tried TCI Wavelog and it works great...!
Congratulations!

My question is, is the feature implemented that automatically changes the radio frequency when you click on a station in the cluster?

Using an ICOM and WavelogGate/FLRig it works, but with TCI Wavelog, it doesn't...

Tnx

**Comment by anthonydiiorio** [comment]
Hi! I just released an update with this feature! It was easy to implement 😀

Be sure to set `bandmap: true` it in the config file! More info in the readme.

```
cloudlog:
  server: "https://log.example.com"
  api: "apikey"
  bandmap: true
  rx1port: 54321 # RX1 port for Bandmap
  rx2port: 54322 # RX2 port for Bandmap

tci:
  host: "127.0.0.1:50001"
```
 https://github.com/anthonydiiorio/CloudlogTCI/blob/master/README.md
